apiVersion: v1
kind: Service
metadata:
  name: acmeats-service
  labels:
    app: acmeats
spec:
  type: ClusterIP
  selector:
    app: acmeats
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
